export const SAVE_USERINFO = 'save_userinfo'
export const DELETE_USERINFO = 'delete_userinfo'
export const SAVE_HEADER_TITLE = 'save_header_title'
export const DELETE_HEADER_TITLE = 'delete_header_title'
export const GET_CATEGORY_LIST = 'get_category_list'